// simple seed script for gov_schemes table
const sequelize = require('./config/database');
const Scheme = require('./models/Scheme');

async function seed() {
  await sequelize.sync({ alter: true });

  const schemes = [
    {
      scheme_name: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
      category: 'General',
      income_limit: 600000,
      state: 'All India',
      occupation: 'Farmer',
      benefits: 'Income support of Rs. 6,000 per year in three equal installments',
      official_link: 'https://pmkisan.gov.in/',
    },
    {
      scheme_name: 'Ayushman Bharat - Pradhan Mantri Jan Arogya Yojana (PMJAY)',
      category: 'General',
      income_limit: 500000,
      state: 'All India',
      occupation: 'Any',
      benefits: 'Health insurance coverage up to Rs. 5 lakh per family per year',
      official_link: 'https://pmjay.gov.in/',
    },
    {
      scheme_name: 'Pradhan Mantri Awas Yojana (PMAY)',
      category: 'General',
      income_limit: 600000,
      state: 'All India',
      occupation: 'Any',
      benefits: 'Assistance for construction of pucca house',
      official_link: 'https://pmaymis.gov.in/',
    },
    {
      scheme_name: 'Swachh Bharat Mission (SBM)',
      category: 'General',
      income_limit: null,
      state: 'All India',
      occupation: 'Any',
      benefits: 'Support for sanitation and hygiene',
      official_link: 'https://swachhbharatmission.gov.in/',
    },
    {
      scheme_name: 'Pradhan Mantri Matru Vandana Yojana (PMMVY)',
      category: 'Women',
      income_limit: 800000,
      state: 'All India',
      occupation: 'Pregnant Women',
      benefits: 'Maternity benefit of Rs. 5,000 in three installments',
      official_link: 'https://pmmvy.nic.in/',
    },
    {
      scheme_name: 'Beti Bachao Beti Padhao (BBBP)',
      category: 'Women',
      income_limit: null,
      state: 'All India',
      occupation: 'Families with girl child',
      benefits: 'Promotion of girl child education and welfare',
      official_link: 'https://wcd.nic.in/bbbp',
    },
    {
      scheme_name: 'National Pension Scheme (NPS)',
      category: 'General',
      income_limit: null,
      state: 'All India',
      occupation: 'Any',
      benefits: 'Retirement savings with government co-contribution',
      official_link: 'https://enps.nsdl.com/',
    },
    {
      scheme_name: 'Atal Pension Yojana (APY)',
      category: 'General',
      income_limit: 100000,
      state: 'All India',
      occupation: 'Unorganized sector workers',
      benefits: 'Pension scheme for unorganized sector',
      official_link: 'https://www.npscra.nsdl.co.in/APY.php',
    },
    {
      scheme_name: 'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
      category: 'General',
      income_limit: null,
      state: 'All India',
      occupation: 'Any',
      benefits: 'Life insurance coverage of Rs. 2 lakh',
      official_link: 'https://www.jansuraksha.gov.in/PMJJBY.aspx',
    },
    {
      scheme_name: 'Pradhan Mantri Suraksha Bima Yojana (PMSBY)',
      category: 'General',
      income_limit: null,
      state: 'All India',
      occupation: 'Any',
      benefits: 'Accidental death insurance coverage of Rs. 2 lakh',
      official_link: 'https://www.jansuraksha.gov.in/PMSBY.aspx',
    },
    {
      scheme_name: 'Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)',
      category: 'General',
      income_limit: null,
      state: 'All India',
      occupation: 'Rural households',
      benefits: '100 days of guaranteed wage employment',
      official_link: 'https://nrega.nic.in/',
    },
    {
      scheme_name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
      category: 'General',
      income_limit: null,
      state: 'All India',
      occupation: 'Farmers',
      benefits: 'Crop insurance against natural calamities',
      official_link: 'https://pmfby.gov.in/',
    },
    {
      scheme_name: 'Digital India Programme',
      category: 'General',
      income_limit: null,
      state: 'All India',
      occupation: 'Any',
      benefits: 'Digital literacy and infrastructure development',
      official_link: 'https://digitalindia.gov.in/',
    },
    {
      scheme_name: 'Skill India Mission',
      category: 'Youth',
      income_limit: null,
      state: 'All India',
      occupation: 'Youth',
      benefits: 'Skill development training',
      official_link: 'https://skillindia.nsdcindia.org/',
    },
    {
      scheme_name: 'Startup India',
      category: 'General',
      income_limit: null,
      state: 'All India',
      occupation: 'Entrepreneurs',
      benefits: 'Support for startups including tax benefits and funding',
      official_link: 'https://www.startupindia.gov.in/',
    },
    {
      scheme_name: 'Make in India',
      category: 'General',
      income_limit: null,
      state: 'All India',
      occupation: 'Manufacturers',
      benefits: 'Promotion of manufacturing in India',
      official_link: 'https://www.makeinindia.com/',
    },
    {
      scheme_name: 'Stand Up India',
      category: 'SC/ST/Women',
      income_limit: 10000000,
      state: 'All India',
      occupation: 'Entrepreneurs',
      benefits: 'Bank loans for SC/ST and women entrepreneurs',
      official_link: 'https://www.standupmitra.in/',
    },
    {
      scheme_name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)',
      category: 'Youth',
      income_limit: null,
      state: 'All India',
      occupation: 'Youth',
      benefits: 'Short-term skill training programs',
      official_link: 'https://pmkvy.gov.in/',
    },
    {
      scheme_name: 'National Health Mission (NHM)',
      category: 'General',
      income_limit: null,
      state: 'All India',
      occupation: 'Any',
      benefits: 'Healthcare services in rural and urban areas',
      official_link: 'https://nhm.gov.in/',
    },
    {
      scheme_name: 'Integrated Child Development Services (ICDS)',
      category: 'Women/Children',
      income_limit: null,
      state: 'All India',
      occupation: 'Mothers and children',
      benefits: 'Nutrition, health, and early education services',
      official_link: 'https://icds-wcd.nic.in/',
    },
    // Add more as needed
  ];

  await Scheme.bulkCreate(schemes, { ignoreDuplicates: true });
  console.log('Seed completed');
  process.exit(0);
}

seed();
